### ISSUE TITLE
0.3.15.1 crashes on importing text data

### ISSUE THREAD

**Issue by Lord-Nightmare** [HertzDevil/0CC-FamiTracker#78]
0.3.15.1 crashes outright when importing text data.

"This application has encountered a problem and needs to close.

Unhandled exception C0000005.

A memory dump file has been created<etc>"

**Comment by Lord-Nightmare** [comment]
This seems to be fixed in git sometime before commit 7fbcdd9acb8f0f3683d6aefefd8dff9a80cfbf2e

**Comment by TheWildShadow55** [comment]
I get this error constantly when I try to save a .0cc and come back to it later.
