### ISSUE TITLE
Famitracker keeps crashing everytime I try to open my file

### ISSUE THREAD

**Issue by Howaboutno45** [HertzDevil/0CC-FamiTracker#97]
Everytime I open the finale file, (will be attached), famitracker says it encountered a problem and it needs to close. This also happens with the chaos file, (will be attached). I will attach a screenshot of what happens and the dmp file that it keeps giving me. 
[0CC-Famitracker Bug.zip](https://github.com/HertzDevil/0CC-FamiTracker/files/5533741/0CC-Famitracker.Bug.zip)

**Comment by aouwt** [comment]
I'm not 100% sure, but I do remember having this issue before, and the file turned out to be corrupted or something. Can you open any other files with the program?

I would recommend using the text export to create backups; those are much easier to repair if they get corrupted.

**Comment by Howaboutno45** [comment]
Yes, I can open other files, I recently started working on another song, and it opens just fine. Also, thanks for the tip about text exports, I will remember that.

**Comment by aouwt** [comment]
You're welcome.

**Comment by Howaboutno45** [comment]
It seems that I cannot create a text backup of the finale file, so I guess the file is corrupted, but I do not know how to fix it.

**Comment by aouwt** [comment]
Maybe try through the command line?

`famitracker (ftm file) -export (output file.txt)`

**Comment by Howaboutno45** [comment]
Sorry for not responding, I got distracted with other things. But, I dont know how to do that.

**Comment by aouwt** [comment]
No problem!
Do you know how to use the command prompt in Windows? (If not, that's okay.)

**Comment by Howaboutno45** [comment]
No, I have never used command prompt, only registry editor

**Comment by aouwt** [comment]
To make this as simple as possible, I would recommend putting the executable (`0CC-FT.exe`) and the FTM file in the root directory (`C:/`)
Then, press `Windows key` and `R` at the same time to open up the "Run" dialog, and then in the box, type `cmd.exe` and press enter.
That opens up the command prompt. Then, in the command prompt, type `cd C:/` to navigate to the root directory, where you put the executable and ftm file.
After that's done, type this: `0CC-FT.exe "your file.ftm" -export "your file.txt"` replacing `0CC-FT.exe` with the name of the executable (if you changed it) and `your file.ftm` with the name of the FTM file that has the song. It should then create a .txt file in the root. That is your exported file. Now you can move everything back if desired.
Next, you open up 0CC the normal way and go to file -> import -> Text import, then select `your file.txt` and it should work then.
Hope this helps!

**Comment by Howaboutno45** [comment]
Ok, so I have done everything and I get a new error now. I got a screenshot and will attach it. The error says: Pattern track index out of range: expected [0,28], got 4294967295 At address 0x22050 in PATTERNS. (No txt.file was created btw)
![Error](https://user-images.githubusercontent.com/74382551/104350981-a773d000-54b9-11eb-810e-07f19c47feb8.png)

**Comment by aouwt** [comment]
Alright, after messing around with the files a bit, I was able to recover finale.0cc. :) I'm still working on chaos, I will update later about that. Unfortunately, I had to discard the sequence data so the instruments won't sound right. Anyway, here is the file, and I've also included a text backup in case it glitches out again while saving.

[finale_fixed.zip](https://github.com/HertzDevil/0CC-FamiTracker/files/5805285/finale_fixed.zip)

**Comment by Howaboutno45** [comment]
Thank you, I am really grateful for this. Hopefully I wont have anymore files that glitch out like this. Also, you don't have to fix the chaos file, I have already started working on a new one. Thanks again for the finale file.

**Comment by aouwt** [comment]
Oh, no problem! Yeah, I would recommend using the text export as a backup when saving, it's leagues easier to repair when 0CC decides to go rogue again. Anyway, I like the song! Much better than I can do lol.

You can close this issue now, I don't have the permissions to close issues that aren't mine. There should be a button saying "Close issue" or something like that on this page, just click it.

**Comment by Howaboutno45** [comment]
Alright thanks for your help, I appreciate it. Also thanks for the complement on my song lol, I appreciate it.
